import type { ImageSourcePropType } from 'react-native';

export interface LegacyFrame {
  sourceIndex: number;
  xOffset: number;
  yOffset: number;
}

export interface LegacySlotMeta {
  frameWidthDivisor: number;
  frameCount: number;
  frames: LegacyFrame[];
}

export interface LegacyImageOption {
  key: string;
  label: string;
  metaId: number;
  imageId: number;
  source: ImageSourcePropType;
  width: number;
  height: number;
}

export interface LegacyVariantStyleOption {
  key: string;
  label: string;
  metaId: number;
  baseImageId: number;
  width: number;
  height: number;
  /** Số tông màu khả dụng (tóc). Nếu undefined → không có color variant. */
  numColors?: number;
}

export const PREVIEW_SLOT = 0;

export const BODY_SHEET = {
  source: require('../../../../assets/createcs_legacy/01_core_compositor/body_sheet_family_990xx_confirmed/99000.png'),
  width: 110,
  height: 53,
} as const;

/**
 * 10 body sheet variants đã được tô màu da (Tông 1–10).
 * Index tương ứng với SKIN_COLOR_OPTIONS index.
 */
export const BODY_SKIN_SHEETS = [
  require('../../../../assets/createcs_legacy/01_core_compositor/body_sheet_family_990xx_confirmed/99000.png'),
  require('../../../../assets/createcs_legacy/01_core_compositor/body_sheet_family_990xx_confirmed/99001.png'),
  require('../../../../assets/createcs_legacy/01_core_compositor/body_sheet_family_990xx_confirmed/99002.png'),
] as const;

export const GENDER_OPTIONS = [
  {
    key: 'male',
    label: 'Nam',
    metaId: 79899,
    imageId: 79800,
    source: require('../../../../assets/createcs_legacy/01_core_compositor/gender_base_candidates/meta_79899_base_79800_candidate/images/79800.png'),
    width: 38,
    height: 23,
  },
  {
    key: 'female',
    label: 'Nữ',
    metaId: 79999,
    imageId: 79900,
    source: require('../../../../assets/createcs_legacy/01_core_compositor/gender_base_candidates/meta_79999_base_79900_candidate/images/79900.png'),
    width: 32,
    height: 23,
  },
] as const;

export const DEFAULT_OVERLAY = {
  metaId: 89999,
  imageId: 89900,
  source: require('../../../../assets/createcs_legacy/01_core_compositor/default_overlay_candidates/meta_89999_base_89900_candidate/images/89900.png'),
  width: 41,
  height: 15,
} as const;

export const ELEMENT_OPTIONS = [
  { key: 'hoa', label: 'Hỏa', value: 0 },
  { key: 'loi', label: 'Lôi', value: 1 },
  { key: 'thuy', label: 'Thủy', value: 2 },
] as const;

export const HAIR_STYLE_OPTIONS = {
  male: [
    { key: '501', label: 'Cổ điển', metaId: 50199, baseImageId: 50100, width: 33, height: 26, numColors: 5 },
    { key: '504', label: 'Vuốt dựng', metaId: 50499, baseImageId: 50400, width: 33, height: 31, numColors: 5 },
    { key: '505', label: 'Búi xõa', metaId: 50599, baseImageId: 50500, width: 27, height: 47, numColors: 5 },
  ],
  female: [
    { key: '500', label: 'Búi nơ', metaId: 50099, baseImageId: 50000, width: 38, height: 38, numColors: 5 },
    { key: '502', label: 'Tóc tém', metaId: 50299, baseImageId: 50200, width: 32, height: 31, numColors: 5 },
    { key: '503', label: 'Búi hai bên', metaId: 50399, baseImageId: 50300, width: 40, height: 24, numColors: 5 },
  ],
} as const satisfies Record<'male' | 'female', readonly LegacyVariantStyleOption[]>;

/**
 * Colored PNG variants của từng kiểu tóc — cùng pose (baseImageId), chỉ đổi màu PLTE.
 * Key = baseImageId, Value = array index = hairColorIndex.
 * Generated by Python palette swap script (build-time).
 */
export const HAIR_COLOR_SOURCES: Record<number, readonly ImageSourcePropType[]> = {
  // Male set_501 (5 tông: default + DF1A14 + FF718A + 4B68D6 + 3DB54E)
  50100: [
    require('../../../../assets/createcs_legacy/03_hair/colored/50100_c0.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50100_c1.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50100_c2.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50100_c3.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50100_c4.png'),
  ],
  // Male set_504 (5 tông)
  50400: [
    require('../../../../assets/createcs_legacy/03_hair/colored/50400_c0.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50400_c1.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50400_c2.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50400_c3.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50400_c4.png'),
  ],
  // Male set_505 (5 tông)
  50500: [
    require('../../../../assets/createcs_legacy/03_hair/colored/50500_c0.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50500_c1.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50500_c2.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50500_c3.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50500_c4.png'),
  ],
  // Female set_500 (5 tông)
  50000: [
    require('../../../../assets/createcs_legacy/03_hair/colored/50000_c0.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50000_c1.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50000_c2.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50000_c3.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50000_c4.png'),
  ],
  // Female set_502 (5 tông)
  50200: [
    require('../../../../assets/createcs_legacy/03_hair/colored/50200_c0.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50200_c1.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50200_c2.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50200_c3.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50200_c4.png'),
  ],
  // Female set_503 (5 tông)
  50300: [
    require('../../../../assets/createcs_legacy/03_hair/colored/50300_c0.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50300_c1.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50300_c2.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50300_c3.png'),
    require('../../../../assets/createcs_legacy/03_hair/colored/50300_c4.png'),
  ],
};

export const EYE_STYLE_OPTIONS = {
  male: [
    { key: '605', label: 'Kiên định', metaId: 60599, baseImageId: 60500, width: 20, height: 13 },
    { key: '606', label: 'Giận dữ', metaId: 60699, baseImageId: 60600, width: 19, height: 13 },
    { key: '607', label: 'Lanh lợi', metaId: 60799, baseImageId: 60700, width: 20, height: 13 },
    { key: '603', label: 'Ngây ngô', metaId: 60399, baseImageId: 60300, width: 20, height: 13 },
    { key: '604', label: 'Sắc lạnh', metaId: 60499, baseImageId: 60400, width: 20, height: 13 },
  ],
  female: [
    { key: '600', label: 'Mơ màng', metaId: 60099, baseImageId: 60000, width: 20, height: 13 },
    { key: '601', label: 'Sắc sảo', metaId: 60199, baseImageId: 60100, width: 20, height: 12 },
    { key: '602', label: 'Tinh nghịch', metaId: 60299, baseImageId: 60200, width: 20, height: 12 },
    { key: '608', label: 'Dịu dàng', metaId: 60899, baseImageId: 60800, width: 20, height: 12 },
    { key: '609', label: 'Nũng nịu', metaId: 60999, baseImageId: 60900, width: 19, height: 11 },
  ],
} as const satisfies Record<'male' | 'female', readonly LegacyVariantStyleOption[]>;

// ---------------------------------------------------------------------------
// Palette Color Swap — mirror thuật toán h.a(byte[], int[], int[]) từ Java
// ---------------------------------------------------------------------------

export interface ColorOption {
  label: string;
  swatch: string;     // hex color để hiển thị swatch trong UI
  toColors: number[]; // mảng màu đích (ARGB int, thay thế fromColors tương ứng)
}

/**
 * Màu gốc trong palette PNG tóc — trích từ PLTE thực tế bằng Python.
 * Tất cả 6 file base đều dùng chung 5 màu này (sort by luminance: dark→light).
 * Lưu ý: entry cuối là 0xBDC2FF (không phải 0xBDC3FF — khác 1 bit).
 */
export const HAIR_PALETTE_FROM: readonly number[] = [
  0x262640, 0x3A3B59, 0x56566C, 0x77778D, 0xBDC2FF,
];

/**
 * 5 tông màu tóc — màu chính từ Java reference.
 * Mid-light (~18% pixels) = màu chính; shadow/highlight derive theo %.
 * Primary: #262640 (default), #DF1A14, #FF718A, #4B68D6, #3DB54E
 */
export const HAIR_COLOR_OPTIONS: ColorOption[] = [
  { label: 'Đen',        swatch: '#262640', toColors: [0x262640, 0x3A3B59, 0x56566C, 0x77778D, 0xBDC2FF] },
  { label: 'Đỏ',         swatch: '#DF1A14', toColors: [0x210303, 0x3E0705, 0x730D0A, 0xDF1A14, 0xF09795] },
  { label: 'Hồng',       swatch: '#FF718A', toColors: [0x261014, 0x471F26, 0x843A47, 0xFF718A, 0xFFBFCA] },
  { label: 'Xanh dương', swatch: '#4B68D6', toColors: [0x0B0F20, 0x151D3B, 0x27366F, 0x4B68D6, 0xAEBBEC] },
  { label: 'Xanh lá',    swatch: '#3DB54E', toColors: [0x091B0B, 0x113215, 0x1F5E28, 0x3DB54E, 0xA7DDAF] },
];

/**
 * Màu gốc trong palette PNG thân người (body 99000.png).
 * Thứ tự: dark_shadow → mid → highlight → warm → medium
 */
export const SKIN_PALETTE_FROM: readonly number[] = [
  0x963903, 0xFD985E, 0xFED3BA, 0xFB650E, 0xFC9255,
];

/**
 * 10 tông màu da — derive bằng brightness adjustment (thuật toán h.b từ Java).
 * Từ tối → sáng dần.
 */
export const SKIN_COLOR_OPTIONS: ColorOption[] = [
  { label: 'Vàng',  swatch: '#963903', toColors: [0x963903, 0xFD985E, 0xFED3BA, 0xFB650E, 0xFC9255] },
  { label: 'Trắng', swatch: '#FFE0BD', toColors: [0xD59A85, 0xFFCDB2, 0xFFF4EC, 0xF8A89B, 0xFFBFA0] },
  { label: 'Ngăm',  swatch: '#8D5524', toColors: [0x381C08, 0x754218, 0xB57A4A, 0x5E3111, 0x6B3914] },
];

export const SLOT_ZERO_META: Record<number, LegacySlotMeta> = {
  79899: {
    frameWidthDivisor: 2,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 22, yOffset: 28 },
      { sourceIndex: 1, xOffset: 22, yOffset: 27 },
    ],
  },
  79999: {
    frameWidthDivisor: 2,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 24, yOffset: 29 },
      { sourceIndex: 1, xOffset: 24, yOffset: 28 },
    ],
  },
  89999: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 7, yOffset: 37 },
      { sourceIndex: 0, xOffset: 7, yOffset: 36 },
    ],
  },
  50099: {
    frameWidthDivisor: 2,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 14, yOffset: -2 },
      { sourceIndex: 1, xOffset: 14, yOffset: -3 },
    ],
  },
  50199: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 13, yOffset: -3 },
      { sourceIndex: 0, xOffset: 13, yOffset: -4 },
    ],
  },
  50299: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 15, yOffset: 0 },
      { sourceIndex: 0, xOffset: 15, yOffset: -1 },
    ],
  },
  50399: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 14, yOffset: -2 },
      { sourceIndex: 0, xOffset: 14, yOffset: -3 },
    ],
  },
  50499: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 17, yOffset: -3 },
      { sourceIndex: 0, xOffset: 17, yOffset: -4 },
    ],
  },
  50599: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: -6 },
      { sourceIndex: 0, xOffset: 19, yOffset: -7 },
    ],
  },
  60099: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
      { sourceIndex: 0, xOffset: 19, yOffset: 13 },
    ],
  },
  60199: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 15 },
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
    ],
  },
  60299: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 15 },
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
    ],
  },
  60399: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
      { sourceIndex: 0, xOffset: 19, yOffset: 13 },
    ],
  },
  60499: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
      { sourceIndex: 0, xOffset: 19, yOffset: 13 },
    ],
  },
  60599: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
      { sourceIndex: 0, xOffset: 19, yOffset: 13 },
    ],
  },
  60699: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 20, yOffset: 14 },
      { sourceIndex: 0, xOffset: 20, yOffset: 13 },
    ],
  },
  60799: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
      { sourceIndex: 0, xOffset: 19, yOffset: 13 },
    ],
  },
  60899: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 19, yOffset: 15 },
      { sourceIndex: 0, xOffset: 19, yOffset: 14 },
    ],
  },
  60999: {
    frameWidthDivisor: 1,
    frameCount: 2,
    frames: [
      { sourceIndex: 0, xOffset: 20, yOffset: 16 },
      { sourceIndex: 0, xOffset: 20, yOffset: 15 },
    ],
  },
};
