import { StyleSheet } from 'react-native';

const SUB_BOX_BG = '#f0f4ff';
const BOX_BORDER = '#99bbee';
const VALUE_BLUE = '#1e40af';

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 900,
    elevation: 900,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  dialogFrame: {
    alignSelf: 'center',
  },
  dialogContent: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dialogScrollContent: {
    alignItems: 'center',
    paddingBottom: 2,
  },
  panelBody: {
    width: '100%',
    gap: 7,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  titleRowCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  titleText: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: '#111',
    textAlign: 'center',
  },
  titleSubText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#444',
  },
  infoRows: {
    gap: 4,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 22,
  },
  infoLabel: {
    width: 76,
    fontSize: 12,
    color: '#333',
  },
  divider: {
    height: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: BOX_BORDER,
  },
  dividerMark: {
    width: 24,
    color: BOX_BORDER,
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  valueBox: {
    minWidth: 56,
    height: 22,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: BOX_BORDER,
    borderRadius: 3,
    backgroundColor: SUB_BOX_BG,
    alignItems: 'center',
    justifyContent: 'center',
  },
  valueBoxWide: {
    flex: 1,
  },
  valueText: {
    fontSize: 12,
    color: VALUE_BLUE,
    fontWeight: '700',
  },
  statRows: {
    gap: 4,
  },
  statRow: {
    height: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  statLabel: {
    width: 80,
    fontSize: 13,
    color: '#333',
    fontWeight: '700',
  },
  primaryText: {
    color: '#ef4444',
  },
  actionButton: {
    minWidth: 26,
    height: 22,
    paddingHorizontal: 7,
    borderWidth: 1,
    borderColor: '#1d4ed8',
    borderRadius: 3,
    backgroundColor: '#e8f0ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonDisabled: {
    borderColor: '#b6c1d2',
    backgroundColor: '#edf1f6',
  },
  actionButtonText: {
    fontSize: 13,
    color: '#1d4ed8',
    fontWeight: '800',
  },
  actionButtonTextDisabled: {
    color: '#9aa6b8',
  },
  statArrowButton: {
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statArrowButtonDisabled: {
    opacity: 0.35,
  },
  statArrowFrame: {
    width: 12,
    height: 12,
    overflow: 'hidden',
  },
  statArrowSheet: {
    position: 'absolute',
    top: 0,
    width: 48,
    height: 12,
  },
  combatGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  combatCol: {
    flex: 1,
    gap: 4,
  },
  combatRow: {
    height: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  combatLabel: {
    flex: 1,
    fontSize: 12,
    color: '#333',
  },
  potentialBody: {
    gap: 6,
  },
  statusHeader: {
    gap: 6,
  },
  statusNameRow: {
    height: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusUsername: {
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    color: '#111',
  },
  statusLevel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#444',
  },
  statusHeaderContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  statusAvatarPanel: {
    width: 80,
    gap: 3,
  },
  statusAvatarBox: {
    width: 80,
    height: 100,
    borderWidth: 1,
    borderColor: '#2255bb',
    backgroundColor: '#fff',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusAvatarInner: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  statusWalletText: {
    height: 15,
    fontSize: 14,
    fontWeight: '800',
    color: '#5c3600',
  },
  statusInfoPanel: {
    flex: 1,
    gap: 3,
    paddingTop: 3,
  },
  statusInfoRow: {
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusInfoLabel: {
    width: 65,
    fontSize: 11,
    color: '#333',
  },
  statusBars: {
    gap: 4,
  },
  statusBarRow: {
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusBarIconCell: {
    width: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBarWrapper: {
    flex: 1,
    height: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#666',
    borderRadius: 3,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
  },
  statusBarFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: '100%',
    borderRightWidth: 1,
    borderRightColor: 'rgba(0,0,0,0.1)',
  },
  statusBarText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#333',
    textAlign: 'center',
    zIndex: 2,
  },
  statusPointsRow: {
    height: 22,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
  },
  statusPointsLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#000',
  },
  statusPointsBox: {
    width: 80,
    height: 20,
    backgroundColor: '#dcc69d',
    borderWidth: 1,
    borderColor: '#8B4513',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusPointsValue: {
    fontSize: 12,
    fontWeight: '800',
    color: '#5c3600',
  },
  skillsBody: {
    minHeight: 430,
  },
  skillTree: {
    width: 316,
    height: 316,
    alignSelf: 'center',
    position: 'relative',
  },
  skillTreeBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  skillTreeHalf: {
    position: 'absolute',
    left: 41,
    top: 13,
    width: 119,
    height: 290,
  },
  skillTreeHalfMirror: {
    left: 159,
    transform: [{ scaleX: -1 }],
  },
  skillNode: {
    position: 'absolute',
    width: 44,
    height: 44,
    borderWidth: 2,
    borderColor: '#d99025',
    backgroundColor: '#2b1a12',
  },
  skillIcon: {
    width: '100%',
    height: '100%',
  },
  skillLevel: {
    position: 'absolute',
    right: 2,
    bottom: 0,
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  skillUpgradeButton: {
    position: 'absolute',
    right: -6,
    top: -6,
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skillUpgradeButtonDisabled: {
    opacity: 0.45,
  },
  skillUpgradeIcon: {
    width: 11,
    height: 11,
  },
  skillInfoCompact: {
    minHeight: 36,
    gap: 2,
  },
  skillInfoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111',
  },
  skillInfoText: {
    fontSize: 12,
    color: '#333',
  },
  sectionTitle: {
    fontSize: 14,
    color: '#1e3a8a',
    fontWeight: '700',
  },
  listScroll: {
    maxHeight: 360,
  },
  listContent: {
    gap: 6,
    paddingBottom: 6,
  },
  listRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#b8cbe9',
    borderRadius: 4,
    backgroundColor: '#f7fbff',
    padding: 6,
  },
  listTextBlock: {
    flex: 1,
    gap: 2,
  },
  listTitle: {
    fontSize: 12,
    color: '#1f2937',
    fontWeight: '700',
  },
  listSubText: {
    fontSize: 11,
    color: '#52647c',
    lineHeight: 14,
  },
  emptyText: {
    fontSize: 12,
    color: '#64748b',
  },
  inventoryBody: {
    width: 390,
    height: 506,
    position: 'relative',
    alignSelf: 'center',
  },
  inventoryNameRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inventoryName: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    color: '#111',
  },
  inventoryLevel: {
    fontSize: 18,
    color: '#333',
  },
  equipSlot: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderWidth: 2,
    borderColor: '#b7c3c7',
    backgroundColor: '#d9d9d9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  equipSlotHat: {
    left: 78,
    top: 36,
  },
  equipSlotArmor: {
    left: 78,
    top: 92,
  },
  equipSlotWeapon: {
    left: 216,
    top: 36,
  },
  equipSlotBoot: {
    left: 216,
    top: 92,
  },
  equipSlotCharm: {
    left: 272,
    top: 36,
  },
  equipSlotAccessory: {
    left: 272,
    top: 92,
  },
  hiddenEquipmentIcon: {
    width: 32,
    height: 32,
    overflow: 'hidden',
  },
  hiddenEquipmentSheet: {
    position: 'absolute',
    top: 0,
    width: 192,
    height: 32,
  },
  equipmentItemIcon: {
    width: 25,
    height: 18,
  },
  inventoryAvatarBox: {
    position: 'absolute',
    left: 134,
    top: 36,
    width: 78,
    height: 96,
    borderWidth: 2,
    borderColor: '#7c9eb2',
    backgroundColor: '#e7fbff',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  capacityText: {
    position: 'absolute',
    left: 0,
    top: 139,
    fontSize: 14,
    color: '#333',
    fontWeight: '700',
  },
  inventoryGrid: {
    position: 'absolute',
    left: 42,
    top: 165,
    width: 306,
    height: 306,
    borderLeftWidth: 1,
    borderTopWidth: 1,
    borderColor: '#a9c2de',
    backgroundColor: '#edf7ff',
  },
  inventoryCell: {
    position: 'absolute',
    width: 51,
    height: 51,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#a9c2de',
    backgroundColor: '#85bef5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inventorySelected: {
    borderColor: '#00bfa5',
    borderWidth: 2,
  },
  inventoryCellIconImage: {
    width: 25,
    height: 18,
  },
  inventoryCellCount: {
    position: 'absolute',
    right: 2,
    bottom: 0,
    fontSize: 14,
    color: '#fff',
    fontWeight: '900',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  tileLevel: {
    position: 'absolute',
    right: 1,
    bottom: -1,
    fontSize: 13,
    color: '#d97706',
    fontWeight: '900',
  },
  inventoryActionRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 476,
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inventorySelectionText: {
    flex: 1,
    fontSize: 12,
    color: '#333',
    fontWeight: '700',
  },
});
