import { StyleSheet } from 'react-native';

const SUB_BOX_BG = '#f0f4ff';
const BOX_BORDER = '#99bbee';
const VALUE_BLUE = '#1e40af';
const HIDDEN_SLOT_SIZE = 47;

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 900,
    elevation: 900,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  dialogFrame: {
    alignSelf: 'center',
  },
  dialogContent: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dialogScrollContent: {
    alignItems: 'center',
    paddingBottom: 2,
  },
  panelBody: {
    width: '100%',
    gap: 7,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  titleRowCentered: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  titleText: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: '#111',
    textAlign: 'center',
  },
  titleSubText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#444',
  },
  infoRows: {
    gap: 4,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 22,
  },
  infoLabel: {
    width: 76,
    fontSize: 12,
    color: '#333',
  },
  divider: {
    height: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: BOX_BORDER,
  },
  dividerMark: {
    width: 24,
    color: BOX_BORDER,
    fontSize: 10,
    textAlign: 'center',
    fontWeight: '700',
  },
  valueBox: {
    minWidth: 56,
    height: 22,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: BOX_BORDER,
    borderRadius: 3,
    backgroundColor: SUB_BOX_BG,
    alignItems: 'center',
    justifyContent: 'center',
  },
  valueBoxWide: {
    flex: 1,
  },
  valueText: {
    fontSize: 12,
    color: VALUE_BLUE,
    fontWeight: '700',
  },
  statRows: {
    gap: 4,
  },
  statRow: {
    height: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  statLabel: {
    width: 80,
    fontSize: 13,
    color: '#333',
    fontWeight: '700',
  },
  primaryText: {
    color: '#ef4444',
  },
  actionButton: {
    minWidth: 26,
    height: 22,
    paddingHorizontal: 7,
    borderWidth: 1,
    borderColor: '#1d4ed8',
    borderRadius: 3,
    backgroundColor: '#e8f0ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonDisabled: {
    borderColor: '#b6c1d2',
    backgroundColor: '#edf1f6',
  },
  actionButtonText: {
    fontSize: 13,
    color: '#1d4ed8',
    fontWeight: '800',
  },
  actionButtonTextDisabled: {
    color: '#9aa6b8',
  },
  statArrowButton: {
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statArrowButtonDisabled: {
    opacity: 0.35,
  },
  statArrowFrame: {
    width: 12,
    height: 12,
    overflow: 'hidden',
  },
  statArrowSheet: {
    position: 'absolute',
    top: 0,
    width: 48,
    height: 12,
  },
  combatGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  combatCol: {
    flex: 1,
    gap: 4,
  },
  combatRow: {
    height: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  combatLabel: {
    flex: 1,
    fontSize: 12,
    color: '#333',
  },
  potentialBody: {
    gap: 6,
  },
  statusHeader: {
    gap: 6,
  },
  statusNameRow: {
    height: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusUsername: {
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    color: '#111',
  },
  statusLevel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#444',
  },
  statusHeaderContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  statusAvatarPanel: {
    width: 80,
    gap: 3,
  },
  statusAvatarBox: {
    width: 80,
    height: 100,
    borderWidth: 1,
    borderColor: '#2255bb',
    backgroundColor: '#fff',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusAvatarInner: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  statusWalletText: {
    height: 15,
    fontSize: 14,
    fontWeight: '800',
    color: '#5c3600',
  },
  statusInfoPanel: {
    flex: 1,
    gap: 3,
    paddingTop: 3,
  },
  statusInfoRow: {
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusInfoLabel: {
    width: 65,
    fontSize: 11,
    color: '#333',
  },
  statusBars: {
    gap: 4,
  },
  statusBarRow: {
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusBarIconCell: {
    width: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBarWrapper: {
    flex: 1,
    height: 20,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#666',
    borderRadius: 3,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
  },
  statusBarFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: '100%',
    borderRightWidth: 1,
    borderRightColor: 'rgba(0,0,0,0.1)',
  },
  statusBarText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#333',
    textAlign: 'center',
    zIndex: 2,
  },
  statusPointsRow: {
    height: 22,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
  },
  statusPointsLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#000',
  },
  statusPointsBox: {
    width: 80,
    height: 20,
    backgroundColor: '#dcc69d',
    borderWidth: 1,
    borderColor: '#8B4513',
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusPointsValue: {
    fontSize: 12,
    fontWeight: '800',
    color: '#5c3600',
  },
  skillsBody: {
    minHeight: 430,
  },
  skillTree: {
    width: 316,
    height: 316,
    alignSelf: 'center',
    position: 'relative',
  },
  skillTreeBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  skillTreeHalf: {
    position: 'absolute',
    left: 41,
    top: 13,
    width: 119,
    height: 290,
  },
  skillTreeHalfMirror: {
    left: 159,
    transform: [{ scaleX: -1 }],
  },
  skillNode: {
    position: 'absolute',
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
    inventorySelectedFrame: {
    ...StyleSheet.absoluteFillObject,
    top: -1,
    left: -1,
    right: -1,
    bottom: -1,
    zIndex: 10,
  },
  skillNodeSelectedFrame: {
    ...StyleSheet.absoluteFillObject,
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    zIndex: 10,
  },
  skillNodeCorner: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderColor: '#00d2d3',
  },
  skillNodeCornerTopLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 2,
    borderLeftWidth: 2,
  },
  skillNodeCornerTopRight: {
    top: 0,
    right: 0,
    borderTopWidth: 2,
    borderRightWidth: 2,
  },
  skillNodeCornerBottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
  },
  skillNodeCornerBottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 2,
    borderRightWidth: 2,
  },
  skillIcon: {
    width: '100%',
    height: '100%',
  },
  skillLevel: {
    position: 'absolute',
    right: 2,
    bottom: 0,
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  skillUpgradeButton: {
    position: 'absolute',
    right: -6,
    top: -6,
    width: 14,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skillUpgradeButtonDisabled: {
    opacity: 0.45,
  },
  skillUpgradeIcon: {
    width: 11,
    height: 11,
  },
  skillInfoCompact: {
    minHeight: 36,
    gap: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skillInfoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111',
    textAlign: 'center',
  },
  skillInfoText: {
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 14,
    color: '#1e3a8a',
    fontWeight: '700',
  },
  listScroll: {
    maxHeight: 360,
  },
  listContent: {
    gap: 6,
    paddingBottom: 6,
  },
  listRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#b8cbe9',
    borderRadius: 4,
    backgroundColor: '#f7fbff',
    padding: 6,
  },
  listTextBlock: {
    flex: 1,
    gap: 2,
  },
  listTitle: {
    fontSize: 12,
    color: '#1f2937',
    fontWeight: '700',
  },
  listSubText: {
    fontSize: 11,
    color: '#52647c',
    lineHeight: 14,
  },
  emptyText: {
    fontSize: 12,
    color: '#64748b',
  },
  inventoryBody: {
    width: 340,
    minWidth: 340,
    height: 600,
    position: 'relative',
    alignSelf: 'center',
  },
  inventoryNameRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    gap: 8,
  },
  inventoryName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    color: '#111',
  },
  inventoryLevel: {
    fontSize: 15,
    color: '#333',
  },
  equipSlot: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderWidth: 2,
    borderColor: '#b7c3c7',
    backgroundColor: '#d9d9d9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  equipSlotArmor: {
    left: 51,
    top: 46,
  },
  equipSlotWeapon: {
    left: 51,
    top: 102,
  },
  equipSlotHat: {
    left: 189,
    top: 46,
  },
  equipSlotBoot: {
    left: 189,
    top: 102,
  },
  equipSlotMount: {
    left: 245,
    top: 46,
  },
  equipSlotRing: {
    left: 245,
    top: 102,
  },
  hiddenEquipmentIcon: {
    width: HIDDEN_SLOT_SIZE,
    height: HIDDEN_SLOT_SIZE,
    overflow: 'hidden',
  },
  hiddenEquipmentSheet: {
    position: 'absolute',
    top: 0,
    width: 282,
    height: HIDDEN_SLOT_SIZE,
  },
  equipmentItemIcon: {
    width: 47,
    height: 47,
  },
  inventoryAvatarBox: {
    position: 'absolute',
    left: 107,
    top: 46,
    width: 78,
    height: 96,
    borderWidth: 2,
    borderColor: '#7c9eb2',
    backgroundColor: '#e7fbff',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  capacityText: {
    position: 'absolute',
    left: 15,
    top: 154,
    fontSize: 14,
    color: '#333',
    fontWeight: '700',
  },
  inventoryGrid: {
    position: 'absolute',
    left: 15,
    top: 178,
    width: 310,
    height: 310,
    borderWidth: 2,
    borderColor: '#4d83a1',
    backgroundColor: '#edf7ff',
  },
  inventoryCell: {
    position: 'absolute',
    width: 51,
    height: 51,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inventoryCellEmpty: {
    backgroundColor: '#93c6fa',
    borderTopColor: '#ffffff',
    borderLeftColor: '#ffffff',
    borderBottomColor: '#808080',
    borderRightColor: '#808080',
  },
  inventoryCellFilled: {
    backgroundColor: '#ced1cf',
    borderTopColor: '#ffffff',
    borderLeftColor: '#ffffff',
    borderBottomColor: '#808080',
    borderRightColor: '#808080',
  },
  inventorySelected: {
    borderColor: '#00bfa5',
    borderWidth: 2,
  },
  inventoryCellItemBg: {
    width: 44,
    height: 44,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#4d83a1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inventoryCellIconImage: {
    width: 47,
    height: 47,
  },
  inventoryCellCount: {
    position: 'absolute',
    right: 2,
    bottom: 0,
    fontSize: 14,
    color: '#fff',
    fontWeight: '900',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  inventoryDetailPanel: {
    position: 'absolute',
    left: 10,
    width: 320,
    top: 492,
    minHeight: 140,
    backgroundColor: '#ffffff',
    borderWidth: 3,
    borderColor: '#4d83a1',
    borderRadius: 8,
    zIndex: 9999,
    elevation: 9999,
    overflow: 'hidden',
  },
  inventoryDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#f0f9ff',
    borderBottomWidth: 1,
    borderBottomColor: '#bae6fd',
    gap: 8,
  },
  inventoryDetailContent: {
    padding: 10,
  },
  inventoryDetailTitle: {
    flex: 1,
    fontSize: 15,
    color: '#0f172a',
    fontWeight: '900',
  },
  inventoryDetailClose: {
    position: 'absolute',
    right: -4,
    top: -4,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2001,
  },
  inventoryDetailCloseIcon: {
    width: 24,
    height: 24,
  },
  inventoryDetailMeta: {
    fontSize: 12,
    color: '#334155',
    fontWeight: '700',
  },
  inventoryDetailText: {
    fontSize: 11,
    color: '#333',
    lineHeight: 15,
  },
  inventoryDetailWarn: {
    fontSize: 11,
    color: '#b91c1c',
    fontWeight: '700',
  },
  inventoryBonusGrid: {
    minHeight: 34,
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 2,
  },
  inventoryBonusText: {
    width: 118,
    fontSize: 11,
    color: VALUE_BLUE,
    fontWeight: '700',
  },
  inventoryDetailActions: {
    height: 24,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 6,
  },
  inventoryActionMenu: {
    position: 'absolute',
    width: 92,
    padding: 2,
    borderWidth: 1,
    borderColor: '#2255bb',
    backgroundColor: '#ffffff',
    zIndex: 20,
    elevation: 20,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
  },
  inventoryActionMenuItem: {
    height: 25,
    justifyContent: 'center',
    paddingHorizontal: 8,
    borderRadius: 2,
  },
  inventoryActionMenuItemSelected: {
    borderWidth: 1,
    borderColor: '#1d4ed8',
    backgroundColor: '#4f9bff',
  },
  inventoryActionMenuText: {
    fontSize: 14,
    color: '#222',
    fontWeight: '500',
  },
  inventoryActionMenuTextSelected: {
    color: '#ffffff',
    fontWeight: '800',
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  inventoryActionMenuTextDisabled: {
    color: '#9aa6b8',
  },
});
