import { Dimensions, StyleSheet } from 'react-native';

const { width: SCREEN_W, height: SCREEN_H } = Dimensions.get('window');
const LAYER_BG = 0;
const LAYER_MONSTER = 2;

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#000' },

  scroll: { flex: 1 },
  mapDebugOverlay: {
    position: 'absolute',
    left: 8,
    top: 124,
    zIndex: 250,
    maxWidth: Math.min(SCREEN_W - 16, 460),
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#f7e26b',
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  mapDebugTitle: {
    color: '#f7e26b',
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 14,
  },
  mapDebugText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
  },
  bg: { position: 'absolute', top: 0, left: 0, zIndex: LAYER_BG },
  npcContainer: {
    position: 'absolute',
    zIndex: LAYER_MONSTER,
    overflow: 'visible',
    alignItems: 'center',
  },
  npcLabel: {
    maxWidth: 120,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 14,
    marginBottom: 2,
    textAlign: 'center',
    textShadowColor: '#000000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  missionToastStack: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 92,
    zIndex: 94,
    gap: 6,
    alignItems: 'stretch',
  },
  missionToast: {
    borderWidth: 1,
    borderColor: '#d8a95d',
    backgroundColor: 'rgba(37, 23, 13, 0.9)',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  missionToastTitle: {
    color: '#ffd276',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  missionToastText: {
    color: '#fff2c8',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 2,
  },
  missionToastLine: {
    color: '#f5d89a',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 1,
  },
  missionDialogOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 98,
    alignItems: 'center',
    justifyContent: 'center',
  },
  missionDialogFrame: {
    width: Math.min(SCREEN_W * 0.94, 470),
    maxHeight: Math.min(SCREEN_H * 0.76, 520),
  },
  missionDialogContent: {
    paddingHorizontal: 10,
    paddingVertical: 9,
    backgroundColor: '#fff1c2',
  },
  missionDialogHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#d09a3d',
    paddingBottom: 6,
    marginBottom: 8,
  },
  missionDialogTitle: {
    color: '#7a3b08',
    fontSize: 18,
    fontWeight: '900',
  },
  missionDialogClose: {
    color: '#1d4ed8',
    fontSize: 13,
    fontWeight: '800',
  },
  missionDialogBody: {
    flexDirection: SCREEN_W >= 430 ? 'row' : 'column',
    gap: 8,
  },
  missionListPanel: {
    width: SCREEN_W >= 430 ? 160 : '100%',
    maxHeight: SCREEN_W >= 430 ? 360 : 150,
    borderWidth: 1,
    borderColor: '#d6a24d',
    backgroundColor: '#fff8dd',
    padding: 6,
  },
  missionDetailPanel: {
    flex: 1,
    minHeight: 220,
    borderWidth: 1,
    borderColor: '#d6a24d',
    backgroundColor: '#fffaf0',
    padding: 8,
  },
  missionPanelTitle: {
    color: '#8a5700',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 6,
    marginBottom: 3,
  },
  missionListScroll: {
    maxHeight: 304,
  },
  missionListContent: {
    gap: 5,
  },
  missionListItem: {
    borderWidth: 1,
    borderColor: '#e2c078',
    backgroundColor: '#fffef7',
    paddingHorizontal: 7,
    paddingVertical: 6,
  },
  missionListItemActive: {
    borderColor: '#cc7a16',
    backgroundColor: '#ffe3a1',
  },
  missionListTitle: {
    color: '#3b260f',
    fontSize: 12,
    fontWeight: '800',
  },
  missionListTitleActive: {
    color: '#8a2f00',
  },
  missionListMeta: {
    color: '#7b5a2b',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  missionDetailTitle: {
    color: '#6f2f00',
    fontSize: 16,
    fontWeight: '900',
  },
  missionDetailDesc: {
    color: '#2f1d12',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 5,
  },
  missionTaskLine: {
    color: '#1f2937',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  missionRewardLine: {
    color: '#0f7a37',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  missionEmptyText: {
    color: '#7b5a2b',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  missionActionButton: {
    alignSelf: 'flex-end',
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#1d4ed8',
    backgroundColor: '#e8f0ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  missionActionButtonDisabled: {
    opacity: 0.55,
    borderColor: '#9ca3af',
    backgroundColor: '#edf1f6',
  },
  missionActionButtonText: {
    color: '#1d4ed8',
    fontSize: 13,
    fontWeight: '900',
  },
  npcTalkOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 28,
    zIndex: 95,
    alignItems: 'center',
  },
  npcTalkFrame: {
    width: Math.min(SCREEN_W * 0.88, 360),
  },
  npcTalkContent: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff2c8',
  },
  npcTalkTitle: {
    color: '#8a5700',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 4,
  },
  npcTalkMessage: {
    color: '#2f1d12',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
  },
  pvpOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pvpBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
  },
  pvpFrame: {
    width: Math.min(SCREEN_W * 0.94, 448),
    maxHeight: Math.min(SCREEN_H * 0.58, 380),
  },
  pvpContent: {
    padding: 8,
    backgroundColor: '#dfe9f7',
  },
  pvpIncomingFrame: {
    width: Math.min(SCREEN_W * 0.86, 340),
  },
  pvpIncomingContent: {
    padding: 12,
    backgroundColor: '#fff4d8',
  },
  pvpIncomingText: {
    color: '#2f1d12',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 8,
  },
  pvpIncomingMeta: {
    color: '#7b4c18',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 6,
  },
  pvpHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  pvpTitle: {
    color: '#8a5700',
    fontSize: 24,
    fontWeight: '800',
  },
  pvpHeaderAction: {
    color: '#313338',
    fontSize: 14,
    fontWeight: '700',
  },
  pvpActionDisabled: {
    opacity: 0.45,
  },
  pvpArenaBoard: {
    position: 'relative',
    marginTop: 2,
    borderWidth: 1,
    borderColor: '#96add3',
    backgroundColor: '#f2f8ff',
  },
  pvpList: {
    maxHeight: 220,
    width: '100%',
  },
  pvpListContent: {
    gap: 0,
    paddingBottom: 2,
  },
  pvpLegacyRow: {
    minHeight: 42,
    borderBottomWidth: 1,
    borderBottomColor: '#b9c7df',
    backgroundColor: '#f7fbff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  pvpLegacyRowActive: {
    backgroundColor: '#fff9df',
    borderTopWidth: 2,
    borderTopColor: '#f0b73d',
    borderBottomColor: '#f0b73d',
  },
  pvpLegacyBadge: {
    width: 28,
    color: '#2d64b5',
    fontSize: 10,
    fontWeight: '900',
    textAlign: 'center',
  },
  pvpLegacyTextWrap: {
    flex: 1,
    minWidth: 0,
    marginLeft: 2,
  },
  pvpLegacyName: {
    color: '#1d2f59',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 18,
  },
  pvpLegacyMeta: {
    color: '#2b5ec4',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 15,
    marginTop: 1,
  },
  pvpLegacyStake: {
    width: 34,
    color: '#486ea8',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'right',
  },
  pvpLegacyPreviewCard: {
    position: 'absolute',
    right: 12,
    top: 74,
    width: Math.min(SCREEN_W * 0.54, 212),
    minHeight: 74,
    borderWidth: 2,
    borderColor: '#5ca3ee',
    backgroundColor: '#f6fbff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  pvpArenaEmptyPanel: {
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f6fbff',
    borderTopWidth: 1,
    borderTopColor: '#b9c7df',
    paddingHorizontal: 12,
  },
  pvpArenaEmptyTitle: {
    color: '#1f2f4d',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  pvpArenaEmptyMeta: {
    color: '#496ca5',
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  pvpLegacyPreviewAvatar: {
    width: 62,
    height: 70,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginRight: 8,
  },
  pvpLegacyPreviewInfo: {
    flex: 1,
    minWidth: 0,
  },
  pvpLegacyPreviewName: {
    color: '#1f2f4d',
    fontSize: 14,
    fontWeight: '800',
  },
  pvpLegacyPreviewMeta: {
    color: '#2c3a52',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  pvpOpponentRow: {
    minHeight: 70,
    borderWidth: 1,
    borderColor: '#6f5535',
    backgroundColor: '#f2e0b8',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  pvpOpponentRowActive: {
    borderColor: '#f1c15a',
    backgroundColor: '#fff0c6',
  },
  pvpOpponentAvatar: {
    width: 42,
    height: 58,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginRight: 8,
  },
  pvpPreviewRow: {
    minHeight: 74,
    borderWidth: 1,
    borderColor: '#6f5535',
    backgroundColor: '#f2e0b8',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginTop: 8,
  },
  pvpPreviewAvatar: {
    width: 54,
    height: 68,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginRight: 10,
  },
  pvpOpponentInfo: {
    flex: 1,
    minWidth: 0,
  },
  pvpOpponentName: {
    color: '#2f1d12',
    fontSize: 14,
    fontWeight: '800',
  },
  pvpOpponentMeta: {
    color: '#5d4327',
    fontSize: 11,
    marginTop: 2,
  },
  pvpMiniButton: {
    minWidth: 48,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7c3f21',
    borderWidth: 1,
    borderColor: '#d8a95d',
  },
  pvpMiniButtonText: {
    color: '#fff2d0',
    fontSize: 11,
    fontWeight: '800',
  },
  pvpChallengeForm: {
    gap: 6,
  },
  pvpLabel: {
    color: '#f8e8be',
    fontSize: 12,
    fontWeight: '700',
  },
  pvpInput: {
    minHeight: 34,
    borderWidth: 1,
    borderColor: '#7e5d37',
    backgroundColor: '#f8e8be',
    color: '#2f1d12',
    paddingHorizontal: 10,
    fontSize: 14,
  },
  pvpStakeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pvpStakeInput: {
    flex: 1,
  },
  pvpStakeUnit: {
    width: 86,
    color: '#f8e8be',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  pvpCheckGrid: {
    marginTop: 4,
    gap: 6,
  },
  pvpCheckRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 24,
  },
  pvpCheckBox: {
    width: 18,
    height: 18,
    borderWidth: 1,
    borderColor: '#d8a95d',
    backgroundColor: '#1d1712',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  pvpCheckBoxActive: {
    backgroundColor: '#a8642b',
  },
  pvpCheckMark: {
    color: '#fff4c9',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 14,
  },
  pvpCheckLabel: {
    color: '#f8e8be',
    fontSize: 12,
    fontWeight: '700',
  },
  pvpStatusRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  pvpStatusText: {
    color: '#f8e8be',
    fontSize: 12,
  },
  pvpErrorText: {
    color: '#ff9f9f',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 8,
  },
  pvpEmptyText: {
    color: '#33486c',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 8,
  },
  pvpFooter: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  pvpButton: {
    minWidth: 82,
    minHeight: 30,
    borderWidth: 1,
    borderColor: '#c88b2f',
    backgroundColor: '#fff1cd',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  pvpButtonPrimary: {
    backgroundColor: '#b26a2f',
  },
  pvpButtonDisabled: {
    opacity: 0.55,
  },
  pvpButtonText: {
    color: '#5a3a0f',
    fontSize: 14,
    fontWeight: '800',
  },
  pvpButtonPrimaryText: {
    color: '#fff4c9',
    fontSize: 14,
    fontWeight: '900',
  },
});
