import { HOA_LU_MAP_ASSETS } from './assets';
import { buildHoaLuSurfaces } from './hoaLu.navigation';
import type { SideScrollMapSceneConfig } from '../core';

export const HOA_LU_SCENE_CONFIG: SideScrollMapSceneConfig = {
  mapId: 'Hoa Lu',
  roomId: 1,
  roomLabel: 'Khu 1',
  nativeWidth: 1536,
  nativeHeight: 1024,
  playerScale: 1.6,
  playerSpeed: 1.35,
  playerSpawnRatio: 0.08,
  createCharacterDefaultScale: 2.2,
  playerFootSinkSourcePx: 5,
  groundTileWidth: 124,
  groundTileHeight: 102,
  groundTileOverlap: 20,
  groundRows: 1,
  groundSink: 18,
  groundContactRatio: 0.16,
  groundContactVisualDrop: 4,
  primaryGroundSurfaceId: 'ground_main',
  assets: HOA_LU_MAP_ASSETS,
  buildSurfaces: buildHoaLuSurfaces,
  monsterSpawnGroups: [
    {
      spawnGroupKey: 'hoa_lu_fire_group_a',
      surfaceId: 'ground_main',
      patrolStartRatio: 0.25,
      patrolEndRatio: 0.48,
      spawnStartRatio: 0.32,
      spawnEndRatio: 0.46,
      moveSpeed: 2.2,
    },
    {
      spawnGroupKey: 'hoa_lu_ice_group_a',
      surfaceId: 'ground_main',
      patrolStartRatio: 0.48,
      patrolEndRatio: 0.72,
      spawnStartRatio: 0.50,
      spawnEndRatio: 0.66,
      moveSpeed: 2.6,
    },
    {
      spawnGroupKey: 'hoa_lu_zap_group_a',
      surfaceId: 'ground_main',
      patrolStartRatio: 0.70,
      patrolEndRatio: 0.92,
      spawnStartRatio: 0.76,
      spawnEndRatio: 0.88,
      moveSpeed: 3.0,
    },
  ],
};
